import Fastify, { FastifyReply, FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { PrismaClient, Prisma, OrderStatus } from '@prisma/client';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { z } from 'zod';

export const db = new PrismaClient();
export const app = Fastify({ logger: { redact: ['req.headers.authorization','req.body.phone','req.body.email','req.body.address'] } });
const threshold=()=>Number(process.env.FREE_DELIVERY_THRESHOLD||10000), fee=()=>Number(process.env.DELIVERY_FEE||500);
const hash=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const fail=(reply:FastifyReply,status:number,code:string,message:string,details:unknown={})=>reply.code(status).send({error:{code,message,details}});
const imageSchema=z.object({url:z.string().url(),alt:z.string().min(1).max(200)});
const address=z.object({city:z.string().min(1).max(150),street:z.string().min(1).max(200),house:z.string().min(1).max(30),apartment:z.string().max(30).optional(),postalCode:z.string().regex(/^\d{6}$/).optional()});
const item=z.object({variantId:z.string().uuid(),quantity:z.number().int().min(1).max(100)});
const orderInput=z.object({customerName:z.string().min(2).max(150),phone:z.string().regex(/^\+?[0-9 ()-]{10,25}$/),email:z.string().email().optional(),address,deliveryMethod:z.literal('manual_delivery'),paymentMethod:z.enum(['on_delivery','manual_confirmation']),comment:z.string().max(2000).optional(),personalDataConsent:z.literal(true)});
const productInput=z.object({slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().min(1),description:z.string().default(''),style:z.string(),color:z.string(),colorCode:z.string().nullable().optional(),countryCode:z.string().regex(/^[A-Z]{2}$/).nullable().optional(),images:z.array(imageSchema).max(20).default([]),badge:z.string().nullable().optional(),isActive:z.boolean().default(true),popularity:z.number().int().min(0).default(0)});
const variantInput=z.object({sku:z.string(),sizeLabel:z.string(),sizeCode:z.string(),lengthCm:z.number().int().positive().nullable().optional(),widthCm:z.number().int().positive().nullable().optional(),diameterCm:z.number().int().positive().nullable().optional(),price:z.number().int().nonnegative(),oldPrice:z.number().int().positive().nullable().optional(),stockQuantity:z.number().int().nonnegative(),isActive:z.boolean().default(true)});
function outProduct(p:any,detail=false){const vs=(p.variants||[]).filter((v:any)=>v.isActive&&v.stockQuantity>0);return {id:p.id,slug:p.slug,name:p.name,description:p.description,style:p.style,color:p.color,colorCode:p.colorCode,countryCode:p.countryCode,images:p.images,badge:p.badge,isActive:p.isActive,priceFrom:vs.length?Math.min(...vs.map((v:any)=>v.price)):null,currency:'RUB',...(detail?{variants:vs}: {})};}
async function auth(req:FastifyRequest,reply:FastifyReply){const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return fail(reply,401,'UNAUTHORIZED','Необходим токен корзины');const c=await db.cart.findUnique({where:{tokenHash:hash(h.slice(7))}});if(!c||c.expiresAt<=new Date())return fail(reply,401,'TOKEN_EXPIRED','Токен неизвестен или истёк');(req as any).cart=c;}
async function cartOut(cartId:string){const c=await db.cart.findUnique({where:{id:cartId},include:{items:{include:{variant:{include:{product:true}}}}}});if(!c)return null;const items=c.items.map(i=>({id:i.id,variantId:i.variantId,productSlug:i.variant.product.slug,name:i.variant.product.name,sizeLabel:i.variant.sizeLabel,image:(i.variant.product.images as any[])?.[0]?.url||null,unitPrice:i.variant.price,quantity:i.quantity,lineTotal:i.variant.price*i.quantity,priceChanged:i.unitPrice!==i.variant.price,available:i.variant.isActive&&i.variant.product.isActive?i.variant.stockQuantity:0}));const subtotal=items.reduce((s,i)=>s+i.lineTotal,0);const delivery=subtotal>=threshold()?0:fee();return {items,currency:'RUB',subtotal,delivery,total:subtotal+delivery,freeDeliveryThreshold:threshold(),amountToFreeDelivery:Math.max(0,threshold()-subtotal)};}
async function admin(req:FastifyRequest,reply:FastifyReply){const a=req.headers.authorization;if(!a?.startsWith('Basic '))return fail(reply,401,'UNAUTHORIZED','Требуется авторизация администратора');const [u,p]=Buffer.from(a.slice(6),'base64').toString().split(':');if(u!==process.env.ADMIN_USERNAME||!process.env.ADMIN_PASSWORD_HASH||!bcrypt.compareSync(p,process.env.ADMIN_PASSWORD_HASH))return fail(reply,401,'UNAUTHORIZED','Неверные учетные данные');}

export async function register(){await app.register(cors,{origin:(process.env.CORS_ORIGINS||'http://localhost:3000').split(',')});await app.register(swagger,{openapi:{info:{title:'TÖPP API',version:'1.0.0'}}});await app.register(swaggerUi,{routePrefix:'/docs'});
 app.get('/health',async()=>({status:'ok'}));
 app.setErrorHandler((e,req,reply)=>{if(e instanceof z.ZodError)return fail(reply,422,'VALIDATION_ERROR','Некорректные данные',{fields:e.issues.map(x=>({field:x.path.join('.'),reason:x.code}))});req.log.error(e);return fail(reply,500,'INTERNAL_ERROR','Внутренняя ошибка сервера');});
 app.post('/api/v1/carts',async(_,reply)=>{const token=crypto.randomBytes(32).toString('base64url');const c=await db.cart.create({data:{tokenHash:hash(token),expiresAt:new Date(Date.now()+Number(process.env.CART_TTL_DAYS||30)*86400000)}});return reply.code(201).send({cartToken:token,expiresAt:c.expiresAt.toISOString(),cart:await cartOut(c.id)});});
 app.get('/api/v1/cart',{preHandler:auth},async(req:any)=>cartOut(req.cart.id));
 app.get('/api/v1/products',async(req:any)=>{const q=req.query as any;const ps=await db.product.findMany({where:{isActive:true},include:{variants:true}});let rows=ps.map(p=>[p,p.variants.filter(v=>v.isActive&&v.stockQuantity>0).filter(v=>(!q.style||p.style===q.style)&&(!q.colorCode||p.colorCode===q.colorCode)&&(!q.countryCode||p.countryCode===q.countryCode)&&(!q.size||v.sizeCode===q.size)&&(!q.lengthCm||v.lengthCm===+q.lengthCm)&&(!q.widthCm||v.widthCm===+q.widthCm)&&(!q.minPrice||v.price>=+q.minPrice)&&(!q.maxPrice||v.price<=+q.maxPrice))] as const).filter(([,v])=>v.length);const sort=q.sort||'newest';rows.sort(([a,av],[b,bv])=>sort==='popular'?b.popularity-a.popularity:sort==='price_asc'?Math.min(...av.map(v=>v.price))-Math.min(...bv.map(v=>v.price)):sort==='price_desc'?Math.min(...bv.map(v=>v.price))-Math.min(...av.map(v=>v.price)):sort==='discount'?Math.max(...bv.map(v=>v.oldPrice?(v.oldPrice-v.price)/v.oldPrice:0))-Math.max(...av.map(v=>v.oldPrice?(v.oldPrice-v.price)/v.oldPrice:0)):b.createdAt.getTime()-a.createdAt.getTime());const page=Math.max(1,+(q.page||1)),limit=Math.min(100,Math.max(1,+(q.limit||20)));return {items:rows.slice((page-1)*limit,page*limit).map(([p])=>outProduct(p)),page,limit,total:rows.length,totalPages:Math.ceil(rows.length/limit)};});
 app.get('/api/v1/products/:slug',async(req:any,reply)=>{const p=await db.product.findUnique({where:{slug:req.params.slug},include:{variants:true}});if(!p||!p.isActive||!p.variants.some(v=>v.isActive&&v.stockQuantity>0))return fail(reply,404,'NOT_FOUND','Товар не найден');return outProduct(p,true);});
 app.get('/api/v1/catalog/filters',async()=>{const ps=await db.product.findMany({where:{isActive:true},include:{variants:true}});const vs=ps.flatMap(p=>p.variants.filter(v=>v.isActive&&v.stockQuantity>0));return {styles:[...new Set(ps.map(p=>p.style))].sort(),colors:[...new Set(ps.map(p=>p.colorCode).filter(Boolean))].sort(),countries:[...new Set(ps.map(p=>p.countryCode).filter(Boolean))].sort(),sizes:[...new Map(vs.map(v=>[v.sizeCode,{code:v.sizeCode,label:v.sizeLabel}])).values()],minPrice:vs.length?Math.min(...vs.map(v=>v.price)):null,maxPrice:vs.length?Math.max(...vs.map(v=>v.price)):null,currency:'RUB'};});
 app.post('/api/v1/cart/items',{preHandler:auth},async(req:any,reply)=>{const x=item.parse(req.body),v=await db.variant.findUnique({where:{id:x.variantId},include:{product:true}});if(!v||!v.isActive||!v.product.isActive)return fail(reply,404,'VARIANT_NOT_FOUND','Вариант недоступен');const old=await db.cartItem.findUnique({where:{cartId_variantId:{cartId:req.cart.id,variantId:v.id}}}),qty=x.quantity+(old?.quantity||0);if(qty>v.stockQuantity)return fail(reply,409,'INSUFFICIENT_STOCK','Недостаточно товара в наличии',{variantId:v.id,available:v.stockQuantity});await db.cartItem.upsert({where:{cartId_variantId:{cartId:req.cart.id,variantId:v.id}},create:{cartId:req.cart.id,variantId:v.id,quantity:qty,unitPrice:v.price},update:{quantity:qty}});return cartOut(req.cart.id);});
 app.patch('/api/v1/cart/items/:id',{preHandler:auth},async(req:any,reply)=>{const q=z.object({quantity:z.number().int().min(1).max(100)}).parse(req.body),i=await db.cartItem.findFirst({where:{id:req.params.id,cartId:req.cart.id},include:{variant:true}});if(!i)return fail(reply,404,'NOT_FOUND','Позиция не найдена');if(q.quantity>i.variant.stockQuantity)return fail(reply,409,'INSUFFICIENT_STOCK','Недостаточно товара в наличии',{available:i.variant.stockQuantity});await db.cartItem.update({where:{id:i.id},data:{quantity:q.quantity}});return cartOut(req.cart.id);});
 app.delete('/api/v1/cart/items/:id',{preHandler:auth},async(req:any,reply)=>{await db.cartItem.deleteMany({where:{id:req.params.id,cartId:req.cart.id}});return cartOut(req.cart.id);});
 app.get('/api/v1/favorites',{preHandler:auth},async(req:any)=>{const fs=await db.favorite.findMany({where:{cartId:req.cart.id},include:{product:{include:{variants:true}}}});return {items:fs.map(f=>outProduct(f.product)).filter((p:any)=>p.priceFrom!==null)};});
 app.put('/api/v1/favorites/:productId',{preHandler:auth},async(req:any,reply)=>{const p=await db.product.findUnique({where:{id:req.params.productId},include:{variants:true}});if(!p||!p.isActive||!p.variants.some(v=>v.isActive&&v.stockQuantity>0))return fail(reply,404,'NOT_FOUND','Товар не найден');await db.favorite.upsert({where:{cartId_productId:{cartId:req.cart.id,productId:p.id}},create:{cartId:req.cart.id,productId:p.id},update:{}});const fs=await db.favorite.findMany({where:{cartId:req.cart.id},include:{product:{include:{variants:true}}}});return {items:fs.map(f=>outProduct(f.product)).filter((x:any)=>x.priceFrom!==null)};});
 app.delete('/api/v1/favorites/:productId',{preHandler:auth},async(req:any)=>{await db.favorite.deleteMany({where:{cartId:req.cart.id,productId:req.params.productId}});const fs=await db.favorite.findMany({where:{cartId:req.cart.id},include:{product:{include:{variants:true}}}});return {items:fs.map(f=>outProduct(f.product)).filter((x:any)=>x.priceFrom!==null)};});
 app.get('/api/v1/checkout/options',async()=>({deliveryMethods:[{code:'manual_delivery',name:'Доставка по согласованию'}],paymentMethods:[{code:'on_delivery',name:'Оплата при получении'},{code:'manual_confirmation',name:'По согласованию'}],rules:{currency:'RUB',freeDeliveryThreshold:threshold(),deliveryFee:fee()}}));
 app.post('/api/v1/checkout/quote',{preHandler:auth},async(req:any,reply)=>{const c=await cartOut(req.cart.id);if(!c?.items.length)return fail(reply,409,'EMPTY_CART','Корзина пуста');if(c.items.some(i=>i.priceChanged||i.quantity>i.available))return fail(reply,409,'CART_CHANGED','Цены или остатки изменились');return {...c,...z.object({address,deliveryMethod:z.literal('manual_delivery')}).parse(req.body)};});
 app.post('/api/v1/orders',{preHandler:auth},async(req:any,reply)=>{const data=orderInput.parse(req.body),key=req.headers['idempotency-key'];if(typeof key!=='string'||key.length<8)return fail(reply,422,'MISSING_IDEMPOTENCY_KEY','Требуется Idempotency-Key');const bodyHash=hash(JSON.stringify(data));const existing=await db.order.findUnique({where:{cartId_idempotencyKey:{cartId:req.cart.id,idempotencyKey:key}},include:{items:true}});if(existing){if(existing.requestHash!==bodyHash)return fail(reply,409,'IDEMPOTENCY_CONFLICT','Ключ уже использован с другим запросом');return reply.code(201).send(existing);}try{const order=await db.$transaction(async(tx)=>{const lines=await tx.cartItem.findMany({where:{cartId:req.cart.id},include:{variant:{include:{product:true}}}});if(!lines.length)throw new Error('EMPTY_CART');for(const i of lines)if(!i.variant.isActive||!i.variant.product.isActive||i.variant.stockQuantity<i.quantity||i.unitPrice!==i.variant.price)throw new Error('CART_CHANGED');const subtotal=lines.reduce((s,i)=>s+i.variant.price*i.quantity,0),delivery=subtotal>=threshold()?0:fee();const o=await tx.order.create({data:{cartId:req.cart.id,idempotencyKey:key,requestHash:bodyHash,customerName:data.customerName,phone:data.phone,email:data.email,address:data.address,deliveryMethod:data.deliveryMethod,paymentMethod:data.paymentMethod,comment:data.comment,subtotal,delivery,total:subtotal+delivery,items:{create:lines.map(i=>({variantId:i.variantId,productName:i.variant.product.name,sku:i.variant.sku,sizeLabel:i.variant.sizeLabel,unitPrice:i.variant.price,quantity:i.quantity}))}}});for(const i of lines){await tx.variant.update({where:{id:i.variantId},data:{stockQuantity:{decrement:i.quantity}}});await tx.cartItem.delete({where:{id:i.id}});}return o;});return reply.code(201).send(order);}catch(e:any){if(e.message==='EMPTY_CART')return fail(reply,409,'EMPTY_CART','Корзина пуста');if(e.message==='CART_CHANGED')return fail(reply,409,'CART_CHANGED','Цены или остатки изменились');throw e;}});
 app.post('/api/v1/admin/products',{preHandler:admin},async(req:any,reply)=>{const x=productInput.parse(req.body);const p=await db.product.create({data:{...x,images:x.images}});return reply.code(201).send(p);});
 app.get('/api/v1/admin/orders',{preHandler:admin},async()=>({items:await db.order.findMany({include:{items:true},orderBy:{createdAt:'desc'}})}));
 app.get('/api/v1/admin/orders/:id',{preHandler:admin},async(req:any,reply)=>{const o=await db.order.findUnique({where:{id:req.params.id},include:{items:true}});if(!o)return fail(reply,404,'NOT_FOUND','Заказ не найден');return o;});
 app.patch('/api/v1/admin/orders/:id/status',{preHandler:admin},async(req:any,reply)=>{const next=z.object({status:z.enum(['new','confirmed','cancelled','fulfilled'])}).parse(req.body).status as OrderStatus;const o=await db.order.findUnique({where:{id:req.params.id}});if(!o)return fail(reply,404,'NOT_FOUND','Заказ не найден');const allowed:Record<string,string[]>={new:['confirmed','cancelled'],confirmed:['fulfilled','cancelled'],cancelled:[],fulfilled:[]};if(!allowed[o.status].includes(next))return fail(reply,409,'INVALID_STATUS_TRANSITION','Недопустимый переход статуса');return db.order.update({where:{id:o.id},data:{status:next}});});
 return app;}
if(process.env.NODE_ENV!=='test')register().then(()=>app.listen({host:'0.0.0.0',port:Number(process.env.PORT||8000)}));
